all:
  children:
    VM:
      children:
        node1:
        node2:
    node1:
      hosts:
        RH_prom:
          ansible_host: 192.168.95.245
    node2:
      hosts:
        RH2:
          ansible_host: 192.168.95.236

    alertmanager-servers:
      hosts:
        RH_prom:
        RH2:
	
    vmagent-servers:
      hosts:
        RH_prom:
        RH2:
	
    vmalert-servers:
      hosts:
        RH_prom:
        RH2:
    
    vminsert-servers:
      hosts:
        RH_prom:
        RH2:
    
    vmselect-servers:
      hosts:
        RH_prom:
        RH2:
    
    vmstorage-servers:
      hosts:
        RH_prom:
        RH2:
